### ISSUE TITLE
[FEATURE] 구매 페이지 API

### ISSUE THREAD

**Issue by summit45** [Kusitms-28th-Hicardi-D/Backend-main#6]
## ✏️ Description 
/demo 에서 사용할 API를 구현한다.

## 📝 ToDo
- [x] 데모 요청 API
- [x] 제품 전체 조회 API
- [ ] 제품 조회 API
- [ ] 제품 구매 API
- [x] 제품 등록 API
