### ISSUE TITLE
[FEATURE] 사진 업로드 및 데이터베이스

### ISSUE THREAD

**Issue by summit45** [Kusitms-28th-Hicardi-D/Backend-main#8]
## ✏️ Description 
사용할 사진 및 데이터 베이스 값을 넣는다.

## 📝 ToDo
- [ ] 메인페이지 영상 넣기
- [x] 제품소개 페이지 영상 넣기
- [x] 구매 페이지 사진 넣기

## ETC
aws S3에 사진 저장하고, 그 url을 데이터베이스에 넣을 수 있도록 구현한다.
